### ISSUE TITLE
[Bug] Optifiabric doesn't work

### ISSUE THREAD

**Issue by Cartrigger** [mcxr-org/MCXR#107]
[latest.log](https://github.com/Sorenon/MCXR/files/9257113/latest.log)
Sure, Optifabric isn't very good, but could help Questcraft because it did work (with hand warping)

**Comment by youngchief-btw** [comment]
OptiFine in general is very problematic with various mods. On top of that it's hard to figure out why the cause is because it's not open source. There are various different mods that when combined give you OptiFine parity (including capes) with better performance. I also use QuestCraft on my Quest 2 for standalone gameplay and I get amazing performance with my mods. If you want the list of mods I use, let me know.

**Comment by Cartrigger** [comment]
I know, I'm talking about QCXR, on 1.3 (QCXR version) Optifabric does work, but has issues.
It would be good to have.

**Comment by FedFer98123** [comment]
dude, just use sodium and iris :|

**Comment by CADIndie** [comment]
> dude, just use sodium and iris :|

Not the point...

**Comment by Fishvap** [comment]
I agree with the fact that there is no point in supporting Optifabric, developers suffer because of its closed-source nature. MCXR cannot fix every bug it encounters with Optifabric without being very invasive.

**Comment by CADIndie** [comment]
A general compat layer is not that difficult as we mostly support it already. Since the MCXR team has just grew with me, Flam and Judge helping out with development, I feel like adding more mod compatibility wont be too much of a task.

**Comment by Fishvap** [comment]
I mean good luck working with closed-source, undocumented modifications 😛

**Comment by CADIndie** [comment]
also, https://github.com/Chocohead/OptiFabric
